name = "Mia AI"
client_id = "9c422dedf9e850a1f8fb3078ca747fa7"
application_url = "https://drivenest.info"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers,read_inventory"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete"]
uri = "/api/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/create", "orders/updated"]
uri = "/api/webhooks"

[build]
automatically_update_urls_on_dev = false
