from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

BASE = """<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — Mia AI</title><style>body{{font-family:Inter,system-ui,sans-serif;max-width:900px;margin:48px auto;padding:0 24px;line-height:1.65;color:#172033}}h1{{color:#4f46e5}}h2{{margin-top:32px}}a{{color:#4f46e5}}</style></head><body>{body}</body></html>"""

@router.get("/privacy", response_class=HTMLResponse, include_in_schema=False)
async def privacy():
    return BASE.format(title="Privacy Policy", body="""<h1>Mia AI Privacy Policy</h1><p><strong>Effective date: September 16, 2026</strong></p><p>Mia AI is an embedded Shopify application operated by SafeNestT Inc. Mia helps merchants manage products, imports, analytics, SEO and marketing.</p><h2>Information we process</h2><p>Mia processes Shopify store information required to provide the app, including store identity, products, inventory, orders and customer information when the merchant has granted the corresponding Shopify permissions. Mia also processes account/session information required for authentication and security.</p><h2>How information is used</h2><p>Information is used to authenticate the merchant, operate Shopify features requested by the merchant, generate SEO and marketing content, maintain imports and application security, and provide support.</p><h2>AI processing</h2><p>When a merchant requests AI-generated content, relevant product or store context may be sent to the configured AI provider to generate the requested result. Mia does not intentionally send Shopify credentials or access tokens to the AI provider.</p><h2>Storage and security</h2><p>Shopify access credentials are encrypted at rest. Mia uses HTTPS, webhook HMAC verification, merchant isolation and access controls. Application records are retained only as needed to operate the service and meet legitimate business or legal requirements.</p><h2>Privacy requests</h2><p>Mia supports Shopify's mandatory privacy compliance webhooks for customer data requests, customer redaction and shop redaction. Merchants can also contact support for privacy questions.</p><h2>Contact</h2><p>Email: <a href="mailto:support@drivenest.info">support@drivenest.info</a></p>""")

@router.get("/terms", response_class=HTMLResponse, include_in_schema=False)
async def terms():
    return BASE.format(title="Terms of Service", body="""<h1>Mia AI Terms of Service</h1><p><strong>Effective date: September 16, 2026</strong></p><p>Mia AI is provided by SafeNestT Inc. for Shopify merchants. By installing or using Mia, you agree to use the service lawfully and to maintain the security of your Shopify account.</p><h2>Service</h2><p>Mia provides Shopify product management, imports, analytics, SEO and marketing assistance. AI-generated content is provided as assistance and should be reviewed by the merchant before publication or material business use.</p><h2>Merchant responsibility</h2><p>You are responsible for your Shopify store, the permissions you grant Mia, content you publish, and compliance with applicable laws and platform policies.</p><h2>Changes and termination</h2><p>Access may be suspended for security, abuse, legal or operational reasons. You may uninstall Mia at any time through Shopify.</p><h2>Contact</h2><p>Email: <a href="mailto:support@drivenest.info">support@drivenest.info</a></p>""")

@router.get("/support", response_class=HTMLResponse, include_in_schema=False)
async def support():
    return BASE.format(title="Support", body="""<h1>Mia AI Support</h1><p>Need help with installation, Shopify connection, product imports, SEO, marketing or account access?</p><h2>Support</h2><p>Email <a href="mailto:support@drivenest.info">support@drivenest.info</a> with your shop domain, a description of the issue and the approximate time it occurred.</p><h2>Privacy requests</h2><p>For privacy requests, include your shop domain and the relevant request type. Do not send Shopify passwords, API secrets or access tokens by email.</p>""")
