import { FormEvent, useEffect, useState } from 'react';
import api from '../services/api';

type Product = { id:string; title:string; status?:string; inventory?:number; description?:string };
type Context = { shop:string; revenue:number; counts:{products:number;orders:number;customers:number;inventory_units:number}; products:Product[]; low_stock:Array<{title:string;inventory:number}>; warnings:string[] };
type Message = { role:'mia'|'user'; text:string; artifact?: any };

export default function Mia(){
  const [context,setContext]=useState<Context|null>(null);
  const [selected,setSelected]=useState('');
  const [messages,setMessages]=useState<Message[]>([{role:'mia',text:'I’m Mia — your live Shopify growth copilot. Select a product, then ask me to generate real SEO or ready-to-post marketing.'}]);
  const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
  useEffect(()=>{api.get('/mia/context').then(r=>{setContext(r.data); if(r.data?.products?.[0])setSelected(r.data.products[0].id);}).catch(()=>setContext(null)).finally(()=>setLoading(false));},[]);
  async function send(e:FormEvent){e.preventDefault(); if(!input.trim()||busy)return; const q=input.trim(); setInput(''); await run(q);}
  async function run(q:string){setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const r=await api.post('/mia/chat',{message:selected?`${q}\n[Selected Shopify product: ${selected}]`:q});setMessages(m=>[...m,{role:'mia',text:r.data.answer,artifact:r.data.artifact}]);}catch(err:any){setMessages(m=>[...m,{role:'mia',text:err?.response?.data?.detail||'I could not complete that live Shopify/AI operation.'}]);}finally{setBusy(false);}}
  const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
  const product=context?.products?.find(p=>p.id===selected);
  return <div className="mia-shell">
    <section>
      <div className="mia-hero"><div className="eyebrow">Mia Intelligence · LIVE SHOPIFY + AI</div><h1 className="mia-title">Your store, understood — and ready to grow.</h1><div className="mia-subtitle">Mia reads live Shopify products, sends the selected product to the server-side AI engine, and returns real SEO, marketing and creative work. Nothing is written to Shopify without approval.</div>
      <div className="metric-grid">{[['Products',context?.counts.products??'—'],['Orders',context?.counts.orders??'—'],['Customers',context?.counts.customers??'—'],['Order value',context?money.format(context.revenue):'—']].map(([l,v])=><div className="metric-card" key={l as string}><div className="metric-label">{l}</div><div className="metric-value">{loading?'…':v}</div></div>)}</div></div>
      <div className="panel" style={{marginTop:18}}><div className="panel-title">Product Copilot</div><select value={selected} onChange={e=>setSelected(e.target.value)} style={{width:'100%',padding:11,borderRadius:9,border:'1px solid #cbd5e1'}}>{(context?.products||[]).map(p=><option key={p.id} value={p.id}>{p.title} · {p.inventory ?? '—'} units</option>)}</select><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button className="glow-button" disabled={busy||!selected} onClick={()=>run(`Analyze this product and generate a real SEO package: ${product?.title||''}`)}>✦ Generate SEO</button><button className="glow-button" disabled={busy||!selected} onClick={()=>run(`Generate ready-to-post Facebook, Instagram, TikTok, email and paid-ad marketing for this product: ${product?.title||''}`)}>🚀 Create Marketing</button><button className="glow-button" disabled={busy||!selected} onClick={()=>run(`Analyze this product for weak description, SEO issues and conversion opportunities: ${product?.title||''}`)}>Analyze Product</button></div></div>
      <div className="panel" style={{marginTop:18}}><div className="panel-title">Live catalog signals</div>{context?.low_stock?.length ? context.low_stock.slice(0,8).map(p=><div className="data-row" key={p.title}><span>{p.title}</span><strong>{p.inventory} left</strong></div>):<p>{loading?'Scanning store data…':'No low-stock products in the current data window.'}</p>}{context?.warnings?.map(w=><p key={w} style={{fontSize:12,color:'#b45309'}}>⚠ {w}</p>)}</div>
    </section>
    <aside className="panel chat"><div className="panel-title"><span style={{color:'#67e8f9'}}>●</span> Mia Copilot <span style={{float:'right',fontSize:11,color:'#7f8ba5'}}>LIVE SHOPIFY + AI</span></div><div className="chat-log">{messages.map((m,i)=><div key={i}><div className={`bubble ${m.role}`}>{m.text}</div>{m.artifact?.type==='seo'&&<SEOArtifact artifact={m.artifact}/>} {m.artifact?.type==='marketing'&&<MarketingArtifact artifact={m.artifact}/>}</div>)}{busy&&<div className="bubble mia">Mia is working with the live product and AI engine…</div>}</div><form className="chat-form" onSubmit={send}><input className="chat-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask Mia: generate SEO, Facebook marketing, TikTok, ads…"/><button className="glow-button" disabled={busy}>Ask</button></form></aside>
  </div>
}

function SEOArtifact({artifact}:{artifact:any}){const r=artifact.result;return <div className="panel" style={{margin:'8px 0',background:'#f8fafc'}}><strong>✦ Real SEO Package · {artifact.product?.title}</strong><p><b>SEO title:</b> {r.seo_title}</p><p><b>Meta description:</b> {r.meta_description}</p><p><b>Optimized title:</b> {r.optimized_title}</p><p><b>Keywords:</b> {r.keywords.join(', ')}</p><p><b>Image alt:</b> {r.image_alt_text.join(' · ')}</p><div dangerouslySetInnerHTML={{__html:r.optimized_description_html}}/><a href="/marketing" style={{display:'inline-block',marginTop:8}}>Open SEO workspace →</a></div>}

function MarketingArtifact({artifact}:{artifact:any}){const r=artifact.result;return <div className="panel" style={{margin:'8px 0',background:'#0f172a',color:'white'}}><strong>🚀 Ready-to-Post Marketing · {artifact.product?.title}</strong>{r.image_url&&<img src={r.image_url} alt={artifact.product?.title} style={{width:'100%',maxHeight:220,objectFit:'cover',borderRadius:10,marginTop:8}}/>}<p><b>Facebook:</b> {r.facebook.copy}</p><p><b>Instagram:</b> {r.instagram.copy}</p><p><b>TikTok:</b> {r.tiktok.copy}</p><p><b>Ad:</b> {r.ad.primary_text}</p><p><b>Email:</b> {r.email.subject}</p><a href="/marketing" style={{color:'#67e8f9'}}>Open Marketing Studio →</a></div>}
